import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillInstagram,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import work1 from "../public/work1.png";
import aldo from "../public/aldo.jpeg";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>itsmealdo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/aldo.jpeg" />
      </Head>

      <main className="bg-utama dark:bg-darks bg-repeat">
        <nav className="sticky top-0 z-20 px-10 lg:px-20 backdrop-filter bg-navutama dark:bg-transparent backdrop-blur-lg bg-opacity-50">
          <div className="max-w-5xl lg:max-w-4xl lg:px-20 mx-auto px-10">
            <div className="flex items-center justify-between h-20">
              <h1 className="text-xl font-montbold dark:text-white">
              <Image
                src={aldo}
                alt="profile"
                width={30}
                height={30}
                className="rounded-full mx-auto ring-5 ring-darks mr-3 dark:ring-white inline-block"
              />itsmealdo
              </h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    className="cursor-pointer text-2xl dark:text-white"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <section className="px-10 md:px-20 lg:px-96 pb-20">
          <div className="text-center pt-10 p-10">
            <div className="pb-6">
              <Image
                src={aldo}
                alt="profile"
                width={200}
                height={200}
                className="rounded-full mx-auto ring-5 ring-darks dark:ring-white"
              />
            </div>
            <h2 className="text-5xl py-2 text-teal-600 font-mplusbold font-medium dark:text-white">
              Aldo Saputra
            </h2>
            <h3 className="text-2xl py-2 dark:text-white">
              Students and Programmer Junior
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              Hi, i'm 22 years old a students from State Islamic University of Sultan Syarif Kasim Riau. I love tech, and i can make a some
              Programs in PHP, and now i'm trying learn React JS. Wish me luck
              :)
            </p>
          <div className=" px-10">
            <a href="https://github.com/itsmealdo"><AiFillGithub className="text-3xl text-gray-600 hover:text-second transition duration-300 dark:text-white  dark:hover:text-second inline-block" /></a>
            <a href="https://instagram.com/aldosaaputra"><AiFillInstagram className="text-3xl text-gray-600 hover:text-second transition duration-300 dark:text-white dark:hover:text-second transition duration-300 inline-block" /></a>
            <a href="https://linkedin.com/in/aldosaputra"> <AiFillLinkedin className="text-3xl text-gray-600 hover:text-second transition duration-300 dark:text-white dark:hover:text-second transition duration-300 inline-block" /></a>
          </div>
        </div>

          <div className="flex justify-center bg-darks px-3 py-4 rounded-lg dark:bg-utamadark transition duration-300">
            <div className="text-white font-mplusmed">
              <span>born in Lubuk Alung, Padang Pariaman, West Sumatera</span>
            </div>
          </div>
        </section>

        <section className="px-10 md:px-20 lg:px-96 pb-20">
          <div>
            <h3 className="text-3xl font-bold dark:text-white pb-3 underline underline-offset-8 decoration-second">
              About Me
            </h3>
            <p className="text-md py-2 leading-8  dark:text-white text-justify">
              A man from Pekanbaru, Riau, Indonesia who loves technology since
              childhood. Now I am a student at Sultan Syarif Kasim Riau State
              Islamic University. I'm a junior developer, and I'm trying to
              learn React JS. This portfolio is built with Next JS and Tailwind
              CSS. I love programming, but I'm still a beginner. I'm trying to
              learn more about programming, and I hope I can become a good
              developer one day.
            </p>
          </div>
          <div>
            <h3 className="text-3xl pt-8 font-bold dark:text-white underline underline-offset-8 decoration-second">
              Works
            </h3>
            <div className="shadow-lg rounded-xl my-10 bg-darks flex">
            <Image src={work1} alt="work1" width={300} height={200} className="rounded-xl " />
            <div className="px-5 mt-5">
              <h3 className="text-white font-mplusmed font-bold">Sistem Operasi Pendaftaran Pernikahan SIPKAH</h3>
            </div>
            </div>
            {/* <p className="text-md py-2 leading-8  dark:text-white">
              A man from Pekanbaru, Riau, Indonesia who loves technology since
              childhood. Now I am a student at Sultan Syarif Kasim Riau State
              Islamic University. I'm a junior developer, and I'm trying to
              learn React JS. This portfolio is built with Next JS and Tailwind
              CSS. I love programming, but I'm still a beginner. I'm trying to
              learn more about programming, and I hope I can become a good
              developer one day.
            </p> */}
          </div>
        </section>

        <section className="px-10 md:px-20 lg:px-96 pb-20">
            <div className="text-center">
              <p className="text-sm dark:text-white">Copyright © {new Date().getFullYear()} Aldo Saputra</p>
            </div>
        </section>
      </main>
    </div>
  );
}
