import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillInstagram,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import aldo from "../public/aldo.jpeg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState  } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>itsmealdo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-utama dark:bg-darks">
        <nav className="sticky top-0 z-20 px-10 backdrop-filter bg-navutama dark:bg-transparent backdrop-blur-lg bg-opacity-50">
            <div className="max-w-5xl mx-auto px-4">
              <div className="flex items-center justify-between h-20">
            <h1 className="text-xl font-montbold dark:text-white">itsmealdo</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl dark:text-white" onClick={() => setDarkMode(!darkMode)} />
              </li>
            </ul>
              </div>
            </div>
          </nav>
        <section className="px-10 md:px-20 lg:px-60 min-h-screen">
          <div className="text-center pt-10 p-10">
            <div>
              <Image src={aldo} alt="profile" width={200} height={200} className="rounded-full mx-auto pb-2" />
            </div>
            <h2 className="text-5xl py-2 text-teal-600 font-mplusbold font-medium dark:text-white">
              Aldo Saputra
            </h2>
            <h3 className="text-2xl py-2 dark:text-white">Students and Developer Junior</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
              Hi, i'm 22 years old a students from Sultan Syarif Kasim Riau
              State Islamic University. I love tech, and i can make a some
              Programs in PHP, and now i'm trying learn React JS. Wish me luck
              :)
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-6 py-3 text-gray-600">
            <a href="https://github.com/itsmealdo"><AiFillGithub className="hover:text-darks transition duration-200 dark: hover:hover:text-darks transition duration-200"/></a>
            <a href="https://instagram.com/aldosaaputra"><AiFillInstagram className="dark:text-white hover:text-teal-500 transition duration-200 dark: hover:hover:text-teal-500 transition duration-200"/></a>
            <a><AiFillLinkedin /></a>
          </div>
          {/* <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow- md:h-96 md:w-96">
            <Image src={deved} alt="deved" layout="fill" objectFit="cover" />
          </div> */}
        </section>

        <section className="px-10 md:px-20 lg:px-60">
          <div>
            <h3 className="text-3xl pt-8 font-bold dark:text-white">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
            A man from Pekanbaru, Riau, Indonesia who loves technology since childhood. Now I am a student at Sultan Syarif Kasim Riau State Islamic University. I'm a junior developer, and I'm trying to learn React JS. This portfolio is built with Next JS and Tailwind CSS. I love programming, but I'm still a beginner. I'm trying to learn more about programming, and I hope I can become a good developer one day.
            </p>
          </div>
          <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
            <Image src={design} className="mx-auto" width={100} height={100} />
            <h3 className="text-lg pt-8 pb-2 text-teal-600">
              Beautiful Designs
            </h3>
            <p clasName="text-gray-800 py-1">
              Creating elegant designgs suited for your needs following core
              design theory.
            </p>
            <p clasName="text-gray-800 py-1">Photoshop</p>
            <p clasName="text-gray-800 py-1">Affinity Designer</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
            <Image src={code} className="mx-auto" width={100} height={100} />
            <h3 className="text-lg pt-8 pb-2 text-teal-600">
              Beautiful Designs
            </h3>
            <p clasName="text-gray-800 py-1">
              Creating elegant designgs suited for your needs following core
              design theory.
            </p>
            <p clasName="text-gray-800 py-1">Photoshop</p>
            <p clasName="text-gray-800 py-1">Affinity Designer</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
            <Image
              src={consulting}
              className="mx-auto"
              width={100}
              height={100}
            />
            <h3 className="text-lg pt-8 pb-2 text-teal-600">
              Beautiful Designs
            </h3>
            <p clasName="text-gray-800 py-1">
              Creating elegant designgs suited for your needs following core
              design theory.
            </p>
            <p clasName="text-gray-800 py-1">Photoshop</p>
            <p clasName="text-gray-800 py-1">Affinity Designer</p>
          </div>
          </div>
        </section>
      </main>
    </div>
  );
}
